### PR TITLE
Added requirements.txt and setup files

### PR DESCRIPTION
**Pull request by wfearn**

### CODE REVIEW

**Comment by jefflund** [comment]
Does ankura 2 use numba?

Add in the categories that most setup.py have.

The url is wrong (my fault - I changed my github username)

Probably want to bump the version

Ankura2 will be the master on ankura. While we refer to it as ankura2 now, it should be referred to as such in code.

**Comment by wfearn** [comment]
What does "bump the version" mean? What are the categories that most setup.py have? Shouldn't you know better than I if it uses numba or not?

**Comment by nOkuda** [comment]
I added the numba dependency for pre-ankura 2.  Check in the exponentiated gradient algorithm, which is where I added numba.

(you could also grep to find out where numba is being used)

**Comment by wfearn** [comment]
I just grepped the directory and numba didn't come up so I removed it.
Please answer back to my other questions.

**Comment by jefflund** [comment]
This is ankura 2 which does not have numba. It should be in the ankura 1 requirements but not here is all.

Bump the version means increase the version number from 0.1 to something bigger. Since we're pre-1.0, we are allowed to make breaking changes, so probably just make it 0.2

**Comment by wfearn** [comment]
I made it .6, does that work?

**Comment by jefflund** [comment]
Yeah add it to the PR and I'll accept :)

**Pull request merged**
